apiVersion: project.oddbit.com/v1beta1
kind: ProjectDefinition
metadata:
  name: example-project
spec:
  description: Example project for demonstrating project operator
  requester: alice@example.com
  quota:
    quotaName: x-large
  admins:
    - alice
    - bob
  members:
    - carol
    - david
    - frank
---
apiVersion: project.oddbit.com/v1beta1
kind: ProjectDefinition
metadata:
  name: example-project-custom-quota
spec:
  description: Example project for demonstrating project operator
  requester: alice@example.com
  quota:
    quotaDefinition:
      resourceQuota:
        hard:
          limits.cpu: "50"
          limits.memory: 100Gi
          requests.cpu: "50"
          requests.memory: 100Gi
          requests.storage: 100Gi
  admins:
    - alice
    - bob
  members:
    - carol
    - david
    - frank
