# permissions for end users to edit projectdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectdefinition-editor-role
rules:
- apiGroups:
  - project.oddbit.com
  resources:
  - projectdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.oddbit.com
  resources:
  - projectdefinitions/status
  verbs:
  - get
