---
- name: "{{ ansible_operator_meta.name }} : create namespace"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ansible_operator_meta.name }}"

        # We put the description in display-name because this shows up
        # in the project list [1], although oddly enough it
        # *doesn't* show up in the project detail page. Sometimes
        # you just can't win.
        #
        # [1]: https://console-openshift-console.apps.ocp-prod.massopen.cloud/k8s/cluster/projects
        annotations:
          openshift.io/requester: "{{ requester }}"
          openshift.io/display-name: "{{ description|default(omit) }}"
        labels:
          massopen.cloud/project: "{{ ansible_operator_meta.name }}"

- name: "{{ ansible_operator_meta.name }} : create rolebindings"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: "{{ ansible_operator_meta.name }}-{{ role }}"
        namespace: "{{ ansible_operator_meta.name }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: "{{ project_role_map[role] }}"
      subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: "{{ ansible_operator_meta.name }}-{{ role }}"
  loop_control:
    loop_var: role
  loop: "{{ project_role_map.keys()|list }}"

- name: "{{ ansible_operator_meta.name }} : check for multiple quotas"
  when: >-
    quota.quota_name|default(false) and quota.quota_definition|default(false)
  fail:
    msg: "Only set one of quota.quotaName and quota.quotaDefinition"

- name: "{{ ansible_operator_meta.name }} : handle named quota"
  when: >-
    quota.quota_name|default(false)
  block:
    - name: "{{ ansible_operator_meta.name }} : look up named quota"
      kubernetes.core.k8s_info:
        api_version: "{{ apiVersion }}"
        kind: ProjectQuota
        name: "{{ quota.quota_name }}"
      register: named_quota

    - name: "{{ ansible_operator_meta.name }} : label namespace"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ ansible_operator_meta.name }}"
            namespace: "{{ ansible_operator_meta.name }}"
            labels:
              massopen.cloud/named-quota: "{{ quota.quota_name }}"

    - name: "{{ ansible_operator_meta.name }} : apply quota definition"
      include_tasks: apply-quota.yaml
      vars:
        quotadef: "{{ named_quota.resources[0].spec }}"

- name: "{{ ansible_operator_meta.name }} : handle custom quota"
  when: >-
    quota.quota_definition|default(false)
  block:
    - name: "{{ ansible_operator_meta.name }} : remove quota label"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ ansible_operator_meta.name }}"
            annotations:
              massopen.cloud/named-quota: null
              massopen.cloud/named-quota-hash: null

    - name: "{{ ansible_operator_meta.name }} : apply quota definition"
      include_tasks: apply-quota.yaml
      vars:
        quotadef:
          resourceQuota: "{{ quota.quota_definition.resource_quota|default({}) }}"
          limitRange: "{{ quota.quota_definition.limit_range|default({}) }}"

- name: "{{ ansible_operator_meta.name }} : create groups"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: "{{ ansible_operator_meta.name }}-{{ role }}"
        labels:
          massopen.cloud/project: "{{ ansible_operator_meta.name }}"
      users: "{{ rolemembers[role]|default([]) }}"
  vars:
    rolemembers:
      admin: "{{ admins | default([]) }}"
      member: "{{ members | default([]) }}"
      reader: "{{ readers | default([]) }}"
  loop_control:
    loop_var: role
  loop: "{{ project_role_map.keys()|list }}"
