# Delete objects that aren't cleaned up automatically.
#
# When a ProjectDefinition is deleted, the namespace is cleaned up
# automatically because of the ownerReference pointing at the
# ProjectDefinition. The groups are left dangling, so we just
# delete the explicitly here.
#
# This role is run as part of a finalizer, so the ProjectDefinition
# won't be deleted if this playbooks fails.
#

- name: "{{ ansible_operator_meta.name }} : delete groups"
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: "{{ ansible_operator_meta.name }}-{{ role }}"
        labels:
          massopen.cloud/project: "{{ ansible_operator_meta.name }}"
  loop_control:
    loop_var: role
  loop: "{{ project_role_map.keys()|list }}"
