# Select task list based on `state` variable. This allows us to use
# different logic for create and delete operations.
#

- name: "{{ ansible_operator_meta.name }} : create project"
  include_tasks: create.yaml
  when: >-
    state == "present"

- name: "{{ ansible_operator_meta.name }} : delete project"
  include_tasks: delete.yaml
  when: >-
    state == "absent"
